name: bengrossmann
favicon: null
layout_spectrum: 0.16087558586150408
typography_spectrum: 0.6275431979447603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4635015483945608
  lightness: 0.09525777376256883
  saturation: 0.4013957530260086
  rhythmicContrast: 0.9517063330858946
purpose: []
